### ISSUE TITLE
Partial image decode - premature end of signal detection

### ISSUE THREAD

**Issue by KiwiInNZ** [Digitelektro/MeteorDemod#54]
I've been experimenting with MeteorDemod, comparing the results I'm getting with using meteor_demod and medet_arm.

Example output from a 18 degree pass this morning - https://kiwiweather.com/2022/11/30/images/2022-11-30-18-42-36-METEOR-M_2-fixed-rectified.jpg
This was using:
- .tle - https://kiwiweather.com/2022/11/30/2022-11-30-18-42-36-METEOR-M_2weather.tle
- .wav - https://kiwiweather.com/2022/11/30/audio/2022-11-30-18-42-36-METEOR-M_2.wav

This data shows the pass over New Zealand this morning, which started at 18:42:36 on the 30th Nov 2022 UTC.

However using MeteorDemod, using the command:
`meteordemod -i /home/pi/wxcapture/audio/2022-11-30-18-42-36-METEOR-M_2.wav -t /home/pi/wxcapture/output/2022-11-30-18-42-36-METEOR-M_2weather.tle -o /home/pi/md/ -f jpg`
I'm getting a much shorter output file.
![spread_221_2022-12-1-18-48-9](https://user-images.githubusercontent.com/51867737/204997782-7b6917ab-79a5-4576-8bf8-7bc049370b78.jpg)

I've updated the settings.ini file with the following changes:

- JpgQuality=90 - to cut down the file sizes whilst I am experimenting
- Latitude=-36.920 - for fairly close to where I live in Auckland, New Zealand
- Longitude=-174.800 - note that East has a negative sign, which is the opposite to Google Maps which uses a negative sign for West, not East (ideally this should be documented as this could confuse people, like I was initially, until looking at the projected images which had the image inverted relative to the projection lines)

It looks like the thick black band shown is enough to make the processing think that it has reached the end of the available signal.
![image](https://user-images.githubusercontent.com/51867737/204999812-854220b0-876a-4c06-a4af-a907dffd4acf.png)

Is it possible to make this "end of signal" detection a bit more forgiving?

**Comment by KiwiInNZ** [comment]
I'm not totally sure I've got the co-ordinate signs right as looking at equidistant_221_2022-12-1-18-48-9.jpg:
![equidistant_221_2022-12-1-18-48-9](https://user-images.githubusercontent.com/51867737/205000585-2fd4ef32-8a93-4d9d-95e7-17075fe433a7.jpg)
This has the lines of longitude and latitude look like they are showing the area where New Zealand is, i.e. in the southern Pacific Ocean, not a huge distance from Antarctica, however there are a couple of things which aren't quite right:
- The image is inverted, with the North Island at the lower part of the image and the South Island at the higher part of the image (the example image from my website shows it in the correct orientation)
- The yellow country outlines belong to another country, not sure which
Can you confirm what values for Longitude and Latitude should be used for Auckland, NZ, which is here on Google Maps - https://www.google.co.nz/maps/place/Auckland/ ?
This might also account for why I'm not seeing any city names / outline for NZ.

**Comment by Digitelektro** [comment]
Hi @KiwiInNZ !

Regarding your first comment, different decoder softwares use different algorithms to process the data, hence the result can be different. I did my best I could, currently I don't have idea how it can be more efficient, and to be honest I am satisfied with the result. With adequate antenna and receiver you can get outstanding result, but it might be not performing well with weak signals.
What you can do is to play with the PLL settings at Demodulator section in settings.ini. Especially with constas bandwidth parameter. Also you can turn off WaitForLock. Please note I chose the best values based on my tests.

Regarding your second comment a few things to note:
Please next time open a new ticket, if it is not relevant to the original issue.
Map overlay is calculated based on satellite date-time. Unfortunately satellite sends only the time part, the date have to be provided manually. MeteorDemod use the current date set on the computer by default. However you can pass any date with the -d parameter. Since you received the data one day earlier, you need to manually input the date.
I decoded your file: `meteordemod -i 2022-11-30-18-42-36-METEOR-M_2.wav -t 2022-11-30-18-42-36-METEOR-M_2weather.tle -o ./ -d 30-11-2022`
And here is the result:
![equidistant_IR_2022-11-30-18-48-9](https://user-images.githubusercontent.com/32802255/205023056-20c9cc81-8a82-4411-acb2-33da4cfd5f76.png)

**Comment by KiwiInNZ** [comment]
I've spent quite a few hours experimenting with different values in the demodulator session. I even built a Debian VM for testing on my main desktop as that is a LOT quicker than a Raspberry Pi. But I've not been able to improve over using the default settings in this section (so well done on picking some good ones!).

However using the same .wav file, as I'd been testing with [not the one from above, but the longer of the .wav files I'd shared in other issues], I've been able to get a better image.
![equidistant_221_2022-12-1-18-24-19](https://user-images.githubusercontent.com/51867737/205475051-eabf2b45-5612-4df0-9e5d-03a67a603e29.jpg)

What I did was to generate the .s file using a different demodulator - https://github.com/dbdexter-dev/meteor_demod.

This was done using the following command:
`/usr/local/bin/meteor_demod -B  -r 72000  -m qpsk -o src/2022-09-25-05-55-38-METEOR-M_2.s srv/2022-09-25-05-55-38-METEOR-M_2.wav`

I then just used this .s file as the input:
`meteordemod -i src/2022-12-01-18-21-57-METEOR-M_2.qpsk -t src/2022-12-01-18-21-57-METEOR-M_2weather.tle -f jpg  -d 01-12-2022`

**Comment by KiwiInNZ** [comment]
Repeating with the original file, using meteor_demod, as per previous update:
![equidistant_221_2022-11-30-18-43-29](https://user-images.githubusercontent.com/51867737/205476249-56bc478d-50ec-4302-ba83-b0c6f862096d.jpg)

**Comment by KiwiInNZ** [comment]
I'm also impressed with your code to remove the majority of the noise lines. This is not easy to do from having experimented with it myself - well done!

**Comment by Digitelektro** [comment]
Yes, it is a way to use it together with meteor_demod. Currently I don't know how I could improve the demodulation. I've already re-written the full demodulation process, it improved a lot, but this is the best I could achieve so far. There is a change once I will have time and mood I try to improve it further, but not in the near future.

**Comment by Digitelektro** [comment]
Actually there is no end of signal detection in the code. Detecting the signal is the hard task, as the PLL needs to find and lock on the signal. Once it locked, it is easier to keep track it.

I made some experiment with your wav file, and it seems different PLL settings works better for you.
Here is what I got (the number is the decoded packets):
 - Preprocessing wav with meteor_demod:  4712
 - Default meteordemod settings: 2671
 - CostasBandwidth=40: 4408

Can you please test it with CostasBandwidth=40?

Other notes:
I saw that your wav file's sample rate is 96kHz meanwhile the satellite bandwidth is 120kHz. You can try to save the file with bigger sample rate. (mine is 128kHz)

I use a trick to help the PLL to lock easier since it can lock on the signal only in a certain frequency range. Due to Doppler effect the center frequency of the signal is changing, and it is higher when the satellite comes in sight (when it is on the horizon). Personally I start the recording at 137.103Mhz, so 3kHz above the original center freqency.

**Comment by Digitelektro** [comment]
I made some changes in the code that improved the demodulation performance.
With the changes I was able to decode 4898 packets from your attached wav file with CostasBandwidth set to 70 which is even more than the packets from meteor_demod.
