### ISSUE TITLE
Map alignment

### ISSUE THREAD

**Issue by dom-robinson** [Digitelektro/MeteorDemod#6]
Hi folks - i am working on getting this into https://github.com/jekhokie/raspberry-noaa-v2 as a processing option. I am loving meteordemod - and have it working - however i am struggling with map alignment. 

GIven the only data passed to meteordemod is the day and the .tle file I am assuming that the alignment is evaluated from some data in the .s source file?

If so i wonder why the .s file we already generate (using https://github.com/jekhokie/raspberry-noaa-v2/blob/master/scripts/audio_processors/rtlsdr_m2_lrpt_rx.py ) which works with METDET_ARM (the current M2 decoding) and indeed produces images with meteordemod however since there are no maps with METDET_ARM output I can't be sure the source .s files actually have what meteordemod needs for the accurate overlay.

Or perhaps i need to specufy Date-Time when i pass that into meteordemod as a param? Any tips?

**Comment by Digitelektro** [comment]
Hi! Date parameter is necessary only if the satellite pass was on a different day. How bad is the map alignment? Is it completely off, or just slightly?  

Alignment is calculated the same way as pass prediction works. The algorithm needs the exact date-time. From .s file the satellite's onboard time is extracted, but it doesn't contains the date.

Can you please send me the .s file along with the tle file and the date when it received? For example using wetransfer or something like that, so I can test it.

**Comment by dom-robinson** [comment]
Sorry - missed yr reply! Thankyou.

So here is a dropbox folder (not too worried about access but password ‘demod’ ). It contains sample outputs, source files i used (.s / tle).




also a fuller detail of where i got to with the integration is here :

**Comment by Digitelektro** [comment]
I didn't really get what is the problem. I checked your files, the map alignment is fine, except on one image, where the date seems to be wrong. I also processed the .s file you provided, and I got fine result. 
If your problem is that the map alignment is slightly off (I mean only a few km), then unfortunately this is the best result you can get.
However, I am not satisfied with the result as well, but I haven't found any solution to calculate more accurate pixel geolocations. There is a missing angle that I don't know how to calculate properly, I opened a [forum post](https://gis.stackexchange.com/questions/383263/determine-the-heading-or-azimuth-angle-of-satellite-meteor-m2) about it, once I have the answer, it might be the solution to draw better map overlay.

**Comment by dom-robinson** [comment]
Im so sorry - i realise that the images i shared are actually mapping ok. 

However this one caused me issues. 

![METEOR-M-2-20210224-081858-mercator-ir](https://user-images.githubusercontent.com/30126642/110641514-07c97a00-81aa-11eb-8acc-b64c3ee1c14f.jpg)

Could i ask you to try to decode it from .s for me: Perhaps my problem was my source data.

[https://www.dropbox.com/s/ggw2m5u0g4p7rql/METEOR-M-2-20210224-081858.s?dl=0](https://www.dropbox.com/s/ggw2m5u0g4p7rql/METEOR-M-2-20210224-081858.s?dl=0)

**Comment by Digitelektro** [comment]
I investigated the problem, and as we discussed in Discord, the TLE file that was provided is not up to date, so I am closing this request now.
